// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCOSIE.Infrastructure.Data;

#nullable disable

namespace PortalCOSIE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014033519_CrearDBNet")]
    partial class CrearDBNet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroBoleta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PeriodoIngreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.HasIndex("NumeroBoleta")
                        .IsUnique();

                    b.ToTable("Alumno", (string)null);
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Carrera", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Mecatrónica"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Telemática"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Biónica"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Energía"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "ISISA"
                        });
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Blob")
                        .HasColumnType("int");

                    b.Property<int>("DocumentoEstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TramiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoEstadoId");

                    b.HasIndex("TramiteId");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.DocumentoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DocumentoEstado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sin cargar"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Validado"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Con errores"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Mala calidad"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Documento equivocado"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Corrupto"
                        });
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Personal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("IdPersonal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personal", (string)null);
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.TipoTramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoTramite", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Dictamen interno (CTE)"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Dictamen externo (CGC)"
                        });
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Tramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConclusion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonalId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTramiteId")
                        .HasColumnType("int");

                    b.Property<int>("TramiteEstadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("TramiteEstadoId");

                    b.ToTable("Tramite", (string)null);
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.TramiteEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TramiteEstado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Solicitado"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "En revision"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Documentos pendientes"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Concluido"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Cacelado"
                        });
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.UnidadAprendizaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarreraId");

                    b.ToTable("UnidadAprendizaje", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarreraId = 1,
                            Nombre = "ALGEBRA LINEAL Y NUMEROS COMPLEJOS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 2,
                            CarreraId = 1,
                            Nombre = "ANALISIS Y DISEÑO DE PROGRAMAS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 3,
                            CarreraId = 1,
                            Nombre = "CALCULO DIFERENCIAL E INTEGRAL",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 4,
                            CarreraId = 1,
                            Nombre = "CALCULO VECTORIAL",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 5,
                            CarreraId = 1,
                            Nombre = "CIRCUITOS ELECTRICOS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 6,
                            CarreraId = 1,
                            Nombre = "CIRCUITOS ELECTRICOS AVANZADOS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 7,
                            CarreraId = 1,
                            Nombre = "DIBUJO ASISTIDO POR COMPUTADORA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 8,
                            CarreraId = 1,
                            Nombre = "ECUACIONES DIFERENCIALES",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 9,
                            CarreraId = 1,
                            Nombre = "ELECTRICIDAD Y MAGNETISMO",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 10,
                            CarreraId = 1,
                            Nombre = "ESTRUCTURA Y PROPIEDADES DE LOS MATERIALES",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 11,
                            CarreraId = 1,
                            Nombre = "COMUNICACION ORAL Y ESCRITA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 12,
                            CarreraId = 1,
                            Nombre = "FUNDAMENTOS DE ELECTRONICA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 13,
                            CarreraId = 1,
                            Nombre = "HERRAMIENTAS COMPUTACIONALES",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 14,
                            CarreraId = 1,
                            Nombre = "INGLES I",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 15,
                            CarreraId = 1,
                            Nombre = "INGLES II",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 16,
                            CarreraId = 1,
                            Nombre = "INTRODUCCION A LA MECATRONICA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 17,
                            CarreraId = 1,
                            Nombre = "INTRODUCCION A LA PROGRAMACION",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 18,
                            CarreraId = 1,
                            Nombre = "MECANICA DE LA PARTICULA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 19,
                            CarreraId = 1,
                            Nombre = "MECANICA DEL CUERPO RIGIDO",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 20,
                            CarreraId = 1,
                            Nombre = "PROCESO DE MANUFACTURA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 21,
                            CarreraId = 1,
                            Nombre = "RESISTENCIA DE MATERIALES",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 22,
                            CarreraId = 1,
                            Nombre = "ADMINISTRACION ORGANIZACIONAL",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 23,
                            CarreraId = 1,
                            Nombre = "ANALISIS DE SEÑALES Y SISTEMAS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 24,
                            CarreraId = 1,
                            Nombre = "ANALISIS Y SINTESIS DE MECANISMOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 25,
                            CarreraId = 1,
                            Nombre = "CIRCUITOS LOGICOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 26,
                            CarreraId = 1,
                            Nombre = "DISEÑO BASICO DE ELEMENTOS DE MAQUINAS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 27,
                            CarreraId = 1,
                            Nombre = "DISPOSITIVOS LOGICOS PROGRAMABLES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 28,
                            CarreraId = 1,
                            Nombre = "ELECTRONICA ANALOGICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 29,
                            CarreraId = 1,
                            Nombre = "INGLES III",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 30,
                            CarreraId = 1,
                            Nombre = "LIDERAZGO Y EMPRENDEDORES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 31,
                            CarreraId = 1,
                            Nombre = "MANTENIMIENTO Y SISTEMAS DE MANUFACTURA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 32,
                            CarreraId = 1,
                            Nombre = "MAQUINAS ELECTRICAS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 33,
                            CarreraId = 1,
                            Nombre = "MECANICA DE FLUIDOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 34,
                            CarreraId = 1,
                            Nombre = "MICROPROCESADORES, MICROCONTROLADORES E INTERFAZ",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 35,
                            CarreraId = 1,
                            Nombre = "NEUMATICA E HIDRAULICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 36,
                            CarreraId = 1,
                            Nombre = "OSCILACIONES Y OPTICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 37,
                            CarreraId = 1,
                            Nombre = "PROBABILIDAD Y ESTADISTICA PARA INGENIERIA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 38,
                            CarreraId = 1,
                            Nombre = "PROGRAMACION AVANZADA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 39,
                            CarreraId = 1,
                            Nombre = "SENSORES Y ACONDICIONADORES DE SEÑAL",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 40,
                            CarreraId = 1,
                            Nombre = "SIMULACION ELECTRONICA Y DISEÑO DE CIRCUITOS IMPRESOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 41,
                            CarreraId = 1,
                            Nombre = "SISTEMAS NEURODIFUSOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 42,
                            CarreraId = 1,
                            Nombre = "TEORIA ELECTROMAGNETICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 43,
                            CarreraId = 1,
                            Nombre = "TERMODINAMICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 44,
                            CarreraId = 1,
                            Nombre = "CONTROL CLASICO",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 45,
                            CarreraId = 1,
                            Nombre = "ETICA PARA EL EJERCICIO PROFESIONAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 46,
                            CarreraId = 1,
                            Nombre = "INSTRUMENTACION VIRTUAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 47,
                            CarreraId = 1,
                            Nombre = "MODELADO Y SIMULACION DE SISTEMAS MECATRONICOS",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 48,
                            CarreraId = 1,
                            Nombre = "AUTOMATIZACION INDUSTRIAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 49,
                            CarreraId = 1,
                            Nombre = "DISEÑO AVANZADO DE ELEMENTOS DE MAQUINAS",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 50,
                            CarreraId = 1,
                            Nombre = "FINANZAS E INGENIERIA ECONOMICA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 51,
                            CarreraId = 1,
                            Nombre = "PROCESADOR DIGITAL DE SEÑALES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 52,
                            CarreraId = 1,
                            Nombre = "INGENIERIA AMBIENTAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 53,
                            CarreraId = 1,
                            Nombre = "ECONOMIA Y LOGISTICA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 54,
                            CarreraId = 1,
                            Nombre = "CONTROL DISTRIBUIDO",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 55,
                            CarreraId = 1,
                            Nombre = "TOPICOS AVANZADOS DE ELECTRONICA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 56,
                            CarreraId = 1,
                            Nombre = "DISEÑO AVANZADO Y MANUFACTURA ASISTIDA POR COMPUTADORA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 57,
                            CarreraId = 1,
                            Nombre = "PROYECTO INTEGRADOR",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 58,
                            CarreraId = 1,
                            Nombre = "AUTOMATAS INDUSTRIALES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 59,
                            CarreraId = 1,
                            Nombre = "AUTOMATIZACION DE LINEA DE PRODUCCION",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 60,
                            CarreraId = 1,
                            Nombre = "TOPICOS AVANZADOS DE SENSORES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 61,
                            CarreraId = 1,
                            Nombre = "DESARROLLO EMPRESARIAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 62,
                            CarreraId = 1,
                            Nombre = "SEGURIDAD INDUSTRIAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 63,
                            CarreraId = 1,
                            Nombre = "SISTEMAS OPERATIVOS EN TIEMPO REAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 64,
                            CarreraId = 1,
                            Nombre = "GRAFICACION EN 3D",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 65,
                            CarreraId = 1,
                            Nombre = "PROCESOS INDUSTRIALES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 66,
                            CarreraId = 1,
                            Nombre = "PRODUCCION MAS LIMPIA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 67,
                            CarreraId = 1,
                            Nombre = "USO Y MANTENIMIENTO DE HERRAMENTAL PARA PROC. DE MANUFACTURA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 68,
                            CarreraId = 1,
                            Nombre = "ELECTIVA I",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 69,
                            CarreraId = 1,
                            Nombre = "SISTEMAS DE CALIDAD PARA LA MANUFACTURA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 70,
                            CarreraId = 1,
                            Nombre = "PROTOCOLOS AVANZADOS DE COMUNICACIONES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 71,
                            CarreraId = 1,
                            Nombre = "CONTROL DE SISTEMAS MECATRONICOS",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 72,
                            CarreraId = 1,
                            Nombre = "ELECTRONICA DE POTENCIA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 73,
                            CarreraId = 1,
                            Nombre = "INGENIERIA ASISTIDA POR COMPUTADORA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 74,
                            CarreraId = 1,
                            Nombre = "METODOLOGIA DE LA INVESTIGACION",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 75,
                            CarreraId = 1,
                            Nombre = "PROYECTOS DE INVERSION",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 76,
                            CarreraId = 1,
                            Nombre = "SISTEMAS DE VISION ARTIFICIAL",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 77,
                            CarreraId = 1,
                            Nombre = "MICROCONTROLADORES AVANZADOS",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 78,
                            CarreraId = 1,
                            Nombre = "MERCADOTECNIA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 79,
                            CarreraId = 1,
                            Nombre = "INTEGRACION DE UN SISTEMA ROBOTICO",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 80,
                            CarreraId = 1,
                            Nombre = "VISION ARTIFICIAL APLICADA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 81,
                            CarreraId = 1,
                            Nombre = "ELECTIVA II",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 82,
                            CarreraId = 1,
                            Nombre = "PROCESOS AVANZADOS DE MANUFACTURA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 83,
                            CarreraId = 1,
                            Nombre = "CONTROL DE SISTEMAS ROBOTICOS",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 84,
                            CarreraId = 1,
                            Nombre = "IMPLEMENTACION DE SISTEMAS DIGITALES",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 85,
                            CarreraId = 1,
                            Nombre = "INSTRUMENTACION VIRTUAL APLICADA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 86,
                            CarreraId = 1,
                            Nombre = "MANUFACTURA INTEGRADA POR COMPUTADORA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 87,
                            CarreraId = 1,
                            Nombre = "TOPICOS AVANZADOS DE AUTOMATIZACION",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 88,
                            CarreraId = 1,
                            Nombre = "SISTEMAS AVANZADOS DE MANUFACTURA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 89,
                            CarreraId = 1,
                            Nombre = "CONTROL DE PROCESOS INDUSTRIALES",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 90,
                            CarreraId = 1,
                            Nombre = "CONTROL INTELIGENTE",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 91,
                            CarreraId = 1,
                            Nombre = "DISEÑO DE EQUIPO PARA MANEJO DE MATERIALES",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 92,
                            CarreraId = 1,
                            Nombre = "DISEÑO ERGONOMICO",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 93,
                            CarreraId = 1,
                            Nombre = "PROTOCOLOS DE COMUNICACION INDUSTRIAL",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 94,
                            CarreraId = 1,
                            Nombre = "PROYECTO DE SISTEMAS EMBEBIDOS",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 95,
                            CarreraId = 1,
                            Nombre = "REALIDAD VIRTUAL",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 96,
                            CarreraId = 1,
                            Nombre = "SISTEMAS DE PROCESAMIENTO DIGITAL DE SEÑALES",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 97,
                            CarreraId = 1,
                            Nombre = "TOPICOS AVANZADOS DE SOLDADURA",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 98,
                            CarreraId = 1,
                            Nombre = "CONTROL DE MAQUINAS ELECTRICAS",
                            Semestre = 5
                        },
                        new
                        {
                            Id = 99,
                            CarreraId = 1,
                            Nombre = "ELECTIVA III",
                            Semestre = 5
                        },
                        new
                        {
                            Id = 100,
                            CarreraId = 1,
                            Nombre = "TRABAJO TERMINAL I",
                            Semestre = 5
                        },
                        new
                        {
                            Id = 101,
                            CarreraId = 1,
                            Nombre = "TRABAJO TERMINAL II",
                            Semestre = 5
                        },
                        new
                        {
                            Id = 102,
                            CarreraId = 1,
                            Nombre = "SERVICIO SOCIAL",
                            Semestre = 5
                        },
                        new
                        {
                            Id = 103,
                            CarreraId = 2,
                            Nombre = "PROGRAMACION",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 104,
                            CarreraId = 2,
                            Nombre = "ANALISIS Y DISEÑO DE SISTEMAS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 105,
                            CarreraId = 2,
                            Nombre = "ESTRUCTURA DE DATOS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 106,
                            CarreraId = 2,
                            Nombre = "ADMINISTRACION DE SISTEMAS OPERATIVOS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 107,
                            CarreraId = 2,
                            Nombre = "DISEÑO DIGITAL",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 108,
                            CarreraId = 2,
                            Nombre = "ARQUITECTURA DE COMPUTADORAS",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 109,
                            CarreraId = 2,
                            Nombre = "FUNDAMENTOS DE FISICA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 110,
                            CarreraId = 2,
                            Nombre = "ECUACIONES DIFERENCIALES",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 111,
                            CarreraId = 2,
                            Nombre = "PROBABILIDAD",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 112,
                            CarreraId = 2,
                            Nombre = "CALCULO DIFERENCIAL E INTEGRAL",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 113,
                            CarreraId = 2,
                            Nombre = "VARIABLE COMPLEJA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 114,
                            CarreraId = 2,
                            Nombre = "ALGEBRA LINEAL",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 115,
                            CarreraId = 2,
                            Nombre = "ELECTROMAGNETISMO",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 116,
                            CarreraId = 2,
                            Nombre = "CALCULO MULTIVARIABLE",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 117,
                            CarreraId = 2,
                            Nombre = "ADMINISTRACION ORGANIZACIONAL",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 118,
                            CarreraId = 2,
                            Nombre = "ETICA, PROFESION Y SOCIEDAD",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 119,
                            CarreraId = 2,
                            Nombre = "COMUNICACION ORAL Y ESCRITA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 120,
                            CarreraId = 2,
                            Nombre = "INGLES I",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 121,
                            CarreraId = 2,
                            Nombre = "INGLES II",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 122,
                            CarreraId = 2,
                            Nombre = "PROGRAMACION ESTRUCTURADA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 123,
                            CarreraId = 2,
                            Nombre = "SOCIEDAD, CIENCIA Y TECNOLOGIA",
                            Semestre = 1
                        },
                        new
                        {
                            Id = 124,
                            CarreraId = 2,
                            Nombre = "SEÑALES Y SISTEMAS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 125,
                            CarreraId = 2,
                            Nombre = "PROPAGACION DE ONDAS ELECTROMAGNETICAS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 126,
                            CarreraId = 2,
                            Nombre = "ELECTRONICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 127,
                            CarreraId = 2,
                            Nombre = "TEORIA DE LOS CIRCUITOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 128,
                            CarreraId = 2,
                            Nombre = "TEORIA DE LA INFORMACION",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 129,
                            CarreraId = 2,
                            Nombre = "TEORIA DE LAS COMUNICACIONES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 130,
                            CarreraId = 2,
                            Nombre = "COMUNICACIONES DIGITALES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 131,
                            CarreraId = 2,
                            Nombre = "PROCESAMIENTO DIGITAL DE SEÑALES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 132,
                            CarreraId = 2,
                            Nombre = "TELEFONIA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 133,
                            CarreraId = 2,
                            Nombre = "SISTEMAS CELULARES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 134,
                            CarreraId = 2,
                            Nombre = "PROTOCOLOS DE INTERNET",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 135,
                            CarreraId = 2,
                            Nombre = "SISTEMAS DISTRIBUIDOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 136,
                            CarreraId = 2,
                            Nombre = "INGENIERIA WEB",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 137,
                            CarreraId = 2,
                            Nombre = "PROGRAMACION AVANZADA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 138,
                            CarreraId = 2,
                            Nombre = "BASES DE DATOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 139,
                            CarreraId = 2,
                            Nombre = "TRANSMISION DE DATOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 140,
                            CarreraId = 2,
                            Nombre = "INFORMACION FINANCIERA E INGENIERIA ECONOMICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 141,
                            CarreraId = 2,
                            Nombre = "OPTATIVA I",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 142,
                            CarreraId = 2,
                            Nombre = "INGLES III",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 143,
                            CarreraId = 2,
                            Nombre = "METODOS NUMERICOS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 144,
                            CarreraId = 2,
                            Nombre = "ELECTRONICA PARA COMUNICACIONES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 145,
                            CarreraId = 2,
                            Nombre = "OPTICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 146,
                            CarreraId = 2,
                            Nombre = "DESARROLLO SUSTENTABLE",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 147,
                            CarreraId = 2,
                            Nombre = "ECONOMIA PARA INGENIEROS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 148,
                            CarreraId = 2,
                            Nombre = "INGLES IV",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 149,
                            CarreraId = 2,
                            Nombre = "REDES INALAMBRICAS",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 150,
                            CarreraId = 2,
                            Nombre = "REDES NEURONALES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 151,
                            CarreraId = 2,
                            Nombre = "LOGICA DIFUSA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 152,
                            CarreraId = 2,
                            Nombre = "SISTEMAS DE INFORMACION GEOGRAFICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 153,
                            CarreraId = 2,
                            Nombre = "PROGRAMACION DE DISPOSITIVOS MOVILES",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 154,
                            CarreraId = 2,
                            Nombre = "NORMATIVIDAD EN TELECOMUNICACIONES E INFORMATICA",
                            Semestre = 2
                        },
                        new
                        {
                            Id = 155,
                            CarreraId = 2,
                            Nombre = "REDES INTELIGENTES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 156,
                            CarreraId = 2,
                            Nombre = "LINEAS DE TRANSMISION Y ANTENAS",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 157,
                            CarreraId = 2,
                            Nombre = "SEGURIDAD EN REDES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 158,
                            CarreraId = 2,
                            Nombre = "MULTIMEDIA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 159,
                            CarreraId = 2,
                            Nombre = "BASES DE DATOS DISTRIBUIDAS",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 160,
                            CarreraId = 2,
                            Nombre = "METODOLOGIA DE LA INVESTIGACION",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 161,
                            CarreraId = 2,
                            Nombre = "ADMINISTRACION DE PROYECTOS",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 162,
                            CarreraId = 2,
                            Nombre = "LIDERAZGO Y EMPRENDEDORES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 163,
                            CarreraId = 2,
                            Nombre = "CRIPTOGRAFIA",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 164,
                            CarreraId = 2,
                            Nombre = "MICROONDAS",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 165,
                            CarreraId = 2,
                            Nombre = "PROCESAMIENTO DE IMAGENES",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 166,
                            CarreraId = 2,
                            Nombre = "TELEVISION DIGITAL",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 167,
                            CarreraId = 2,
                            Nombre = "SISTEMAS DE CALIDAD",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 168,
                            CarreraId = 2,
                            Nombre = "PROCESAMIENTO DE VOZ",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 169,
                            CarreraId = 2,
                            Nombre = "FILTRADO AVANZADO",
                            Semestre = 3
                        },
                        new
                        {
                            Id = 171,
                            CarreraId = 2,
                            Nombre = "PROYECTO TERMINAL I",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 172,
                            CarreraId = 2,
                            Nombre = "PROYECTO TERMINAL II",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 173,
                            CarreraId = 2,
                            Nombre = "REDES DE TELECOMUNICACIONES",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 174,
                            CarreraId = 2,
                            Nombre = "APLICACIONES DISTRIBUIDAS",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 175,
                            CarreraId = 2,
                            Nombre = "DISPOSITIVOS PROGRAMABLES",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 176,
                            CarreraId = 2,
                            Nombre = "SERVICIO SOCIAL",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 177,
                            CarreraId = 2,
                            Nombre = "ELECTIVA I",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 178,
                            CarreraId = 2,
                            Nombre = "ELECTIVA II",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 179,
                            CarreraId = 2,
                            Nombre = "ELECTIVA III",
                            Semestre = 4
                        },
                        new
                        {
                            Id = 180,
                            CarreraId = 2,
                            Nombre = "ELECTIVA IV",
                            Semestre = 4
                        });
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Alumno", b =>
                {
                    b.HasOne("PortalCOSIE.Domain.Entities.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCOSIE.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Alumno")
                        .HasForeignKey("PortalCOSIE.Domain.Entities.Alumno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Documento", b =>
                {
                    b.HasOne("PortalCOSIE.Domain.Entities.DocumentoEstado", "DocumentoEstado")
                        .WithMany()
                        .HasForeignKey("DocumentoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalCOSIE.Domain.Entities.Tramite", "Tramite")
                        .WithMany("Documentos")
                        .HasForeignKey("TramiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoEstado");

                    b.Navigation("Tramite");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Personal", b =>
                {
                    b.HasOne("PortalCOSIE.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Personal")
                        .HasForeignKey("PortalCOSIE.Domain.Entities.Personal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Tramite", b =>
                {
                    b.HasOne("PortalCOSIE.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCOSIE.Domain.Entities.Personal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalCOSIE.Domain.Entities.TramiteEstado", "TramiteEstado")
                        .WithMany()
                        .HasForeignKey("TramiteEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Personal");

                    b.Navigation("TramiteEstado");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.UnidadAprendizaje", b =>
                {
                    b.HasOne("PortalCOSIE.Domain.Entities.Carrera", "Carrera")
                        .WithMany("UnidadesAprendizaje")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Carrera", b =>
                {
                    b.Navigation("UnidadesAprendizaje");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Tramite", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("PortalCOSIE.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Alumno")
                        .IsRequired();

                    b.Navigation("Personal")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
